export enum DeliveryStatus {
    NO_RECIBIDO = 'NO_RECIBIDO',
    ANTES_DE_LA_FECHA_ACORDADA = 'ANTES_DE_LA_FECHA_ACORDADA',
    EN_LA_FECHA_ACORDADA = 'EN_LA_FECHA_ACORDADA',
    DESPUES_DE_LA_FECHA_ACORDADA = 'DESPUES_DE_LA_FECHA_ACORDADA'
}