# Configuración específica para desarrollo

# Configuración de BCrypt para desarrollo
bcrypt:
  strength: 10  # Más rápido para desarrollo

# Configuración de JWT para desarrollo
jwt:
  secret: raffyjwtsecretkey2025supersecurefordevelopment
  expiration: 86400000  # 24 horas
  refresh-expiration: 604800000  # 7 días
  issuer: raffy-backend
  audience: raffy-frontend

spring:
  datasource:
    # Configuración de pool de conexiones para desarrollo
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 30000
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Configuración de logging para desarrollo
logging:
  level:
    root: INFO
    com.desarrollo.raffy: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
